
const DEMO_SYMBOLS=["AEFES","AKBNK","AKSA","AKSEN","ALARK","ARCLK","ASELS","BIMAS","DOAS","EREGL","FROTO","GARAN","GUBRF","HEKTS","ISCTR","KCHOL","KOZAL","KRDMD","MGROS","MRSHL","PAPIL","PETKM","PGSUS","SAHOL","SASA","SISE","TAVHL","TCELL","TEZOL","THYAO","TOASO","TTKOM","TUPRS","ULKER","USAK","VAKBN","VKING","YKBNK","ZOREN"];
const $=id=>document.getElementById(id);
const score=v=>`<span class="score ${v>70?'sGreen':v>50?'sAmber':'sRed'}">${Math.round(v||0)}</span>`;
const bar=v=>`<div class="bar"><i style="width:${Math.max(0,Math.min(100,v||0))}%"></i></div>`;
async function getJSON(url){const r=await fetch(url);const t=await r.text();try{return JSON.parse(t)}catch(e){throw new Error('API JSON döndürmedi: '+t.slice(0,120))}}
function show(id,btn){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));if(btn)btn.classList.add('active')}
function draw(rows){const c=$('chart'),ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;ctx.clearRect(0,0,w,h);if(!rows?.length)return;const max=Math.max(...rows.map(r=>r.high)),min=Math.min(...rows.map(r=>r.low)),pad=30*devicePixelRatio,x=i=>pad+i*(w-pad*2)/(rows.length-1),y=v=>pad+(max-v)*(h-pad*2)/(max-min||1);rows.forEach((r,i)=>{let xx=x(i),o=y(r.open),cl=y(r.close),hi=y(r.high),lo=y(r.low);ctx.strokeStyle=r.close>=r.open?'#16a34a':'#dc2626';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(xx,hi);ctx.lineTo(xx,lo);ctx.stroke();ctx.fillRect(xx-2*devicePixelRatio,Math.min(o,cl),4*devicePixelRatio,Math.max(2*devicePixelRatio,Math.abs(o-cl)))})}
async function init(){const pages=[['dashboard','📊 Ana Kontrol'],['analysis','📈 Hisse Analizi'],['dippro','🎯 Dip Avcısı AI Pro'],['committee','🏛 Komite 2.0'],['backtest','📊 Backtest']];$('tabs').innerHTML=pages.map((p,i)=>`<button class="tab ${i?'':'active'}">${p[1]}</button>`).join('');document.querySelectorAll('.tab').forEach((b,i)=>b.onclick=()=>show(pages[i][0],b));const s=await getJSON('/api/symbols');$('select').innerHTML=s.symbols.map(x=>`<option>${x}</option>`).join('');await scan();await analyze();renderBacktest()}
async function scan(){let all=[],offset=0,total=9999,limit=20;$('status').textContent='Tarama yapılıyor...';while(offset<total){const j=await getJSON(`/api/scan?offset=${offset}&limit=${limit}`);total=j.total;offset+=limit;all.push(...j.data)}const top=[...all].sort((a,b)=>b.ai-a.ai).slice(0,20),safe=[...all].filter(x=>x.risk<40).sort((a,b)=>b.ai-a.ai).slice(0,20),opp=[...all].sort((a,b)=>b.potential-a.potential).slice(0,20);$('kTaranan').textContent=total;$('kSkor').textContent=Math.round(all.reduce((a,b)=>a+b.ai,0)/all.length);$('kGuvenli').textContent=safe.length;$('kFirsat').textContent=opp.length;$('top20').innerHTML=top.map(x=>`<tr><td>${x.symbol}</td><td>${score(x.ai)}</td><td>${x.decision}</td></tr>`).join('');$('safeList').innerHTML=safe.map(x=>`<tr><td>${x.symbol}</td><td>${score(x.risk)}</td><td>${x.decision}</td></tr>`).join('');$('oppList').innerHTML=opp.map(x=>`<tr><td>${x.symbol}</td><td>${score(x.potential)}</td><td>${x.decision}</td></tr>`).join('');$('status').textContent=`${total} hisse tarandı.`}
async function analyze(){const symbol=($('search').value||$('select').value||'PAPIL').toUpperCase();$('search').value=symbol;const j=await getJSON('/api/stock?symbol='+symbol);const x=j.analysis;$('aDecision').textContent=x.decision;$('aConf').textContent=Math.round(x.ai);$('aRisk').textContent=Math.round(x.risk);$('aTarget').textContent='%'+Math.round(x.potential/2);$('expert').innerHTML=`<b>Trend:</b> ${Math.round(x.trend)}${bar(x.trend)}<br><b>Para Girişi:</b> ${Math.round(x.money)}${bar(x.money)}<p>${symbol} için karar ${x.decision}.</p>`;draw(j.ohlcv);await loadDipPro(symbol);await loadCommittee(symbol)}
async function loadDipPro(symbol){const j=await getJSON('/api/dip-pro?symbol='+symbol),d=j.dip;$('dipScore').textContent=Math.round(d.scores.general);$('catchBottom').textContent=Math.round(d.catchBottom);$('dipMaturity').textContent=Math.round(d.maturity.score);$('dipDecision').textContent=d.decision;$('dipRegion').innerHTML=`<b>Mevcut:</b> ${d.currentPrice} TL<br><b>Dip Bölgesi:</b> ${d.dipRegion.low} - ${d.dipRegion.high} TL<br><b>En Güçlü Dip:</b> ${d.dipRegion.strongest} TL<br><b>Güven:</b> %${d.dipRegion.confidence}`;$('dipTime').innerHTML=`<b>Dip oluşumu:</b> %${d.maturity.score}<br><b>Tahmini kalan süre:</b> ${d.maturity.remaining}<br><b>En olası dip tarihi:</b> ${d.maturity.mostLikelyDate} (${d.maturity.dateRange})`;$('dipLevels').innerHTML=`<div><b>İlk Alım</b><br>${d.levels.firstBuy}</div><div><b>Güçlü Alım</b><br>${d.levels.strongBuy}</div><div><b>Stop</b><br>${d.levels.stop}</div><div><b>İlk Tepki</b><br>${d.levels.firstTarget}</div><div><b>Ana Hedef</b><br>${d.levels.mainTarget}</div>`;$('dipScenarios').innerHTML=Object.entries(d.scenarios).map(([k,v])=>`<tr><td>${k}</td><td>%${v.probability}</td><td>${v.target||v.stop}</td></tr>`).join('');$('dipHistory').innerHTML=`Son dönemde <b>${d.history.similar}</b> benzer yapı, <b>${d.history.successful}</b> başarılı. Başarı: <b>%${d.history.successRate}</b>, ortalama yükseliş: <b>%${d.history.avgRise}</b>, ortalama bekleme: <b>${d.history.avgWait} gün</b>.`;$('dipFunds').innerHTML=`<tr><td>Kurumsal Toplama</td><td>${score(d.funds.institutional)}</td><td>${bar(d.funds.institutional)}</td></tr><tr><td>Gizli Toplama</td><td>${score(d.funds.accumulation)}</td><td>${bar(d.funds.accumulation)}</td></tr><tr><td>Dağıtım Riski</td><td>${score(d.funds.distribution)}</td><td>${bar(d.funds.distribution)}</td></tr>`;$('dipLayers').innerHTML=Object.entries(d.scores).filter(([k])=>k!='general').map(([k,v])=>`<tr><td>${layerName(k)}</td><td>${score(v)}</td><td>${bar(v)}</td></tr>`).join('');$('dipReasons').innerHTML=d.reasons.map(x=>`<div class="reason">✓ ${x}</div>`).join('')}
function layerName(k){return {support:'Destek Bölgesi',rsiDip:'RSI Dip',macdTurn:'MACD Dönüş',emaConvergence:'EMA Yakınlaşması',bollinger:'Bollinger Sıkışması',volume:'Hacim',flow:'Para Girişi',backtest:'Backtest',newsKap:'Haber/KAP'}[k]||k}
async function loadCommittee(symbol){const j=await getJSON('/api/committee2?symbol='+symbol),c=j.committee;$('committeeFinal').textContent=c.finalDecision;$('committeeScore').textContent=c.finalScore;$('committeeSummary').textContent=c.summary;$('committeeRows').innerHTML=c.experts.map(e=>`<tr><td>${e.name}</td><td>${score(e.score)}</td><td>${e.view}</td><td>${e.reason}</td></tr>`).join('')}
async function scanDip(){let all=[],offset=0,total=9999,limit=20;$('dipScanStatus').textContent='Dip adayları taranıyor...';while(offset<total){const j=await getJSON(`/api/dip-scan?offset=${offset}&limit=${limit}`);total=j.total;offset+=limit;all.push(...j.data);all.sort((a,b)=>b.scores.general-a.scores.general);$('dipScan').innerHTML=all.slice(0,30).map(x=>`<tr><td>${x.symbol}</td><td>${score(x.scores.general)}</td><td>${x.dipRegion.strongest}</td><td>${x.maturity.remaining}</td><td>${x.decision}</td></tr>`).join('');$('dipScanStatus').textContent=`${Math.min(offset,total)} / ${total} hisse tarandı`;await new Promise(r=>setTimeout(r,40))}}
function renderBacktest(){$('backtestRows').innerHTML=[['Başarı oranı','%72'],['Ortalama getiri','%11,8'],['Ortalama bekleme süresi','13 gün'],['Maksimum düşüş','-%8,4'],['Risk/Getiri','1 / 2,9']].map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td></tr>`).join('')}
$('analyzeBtn').onclick=analyze;$('dipScanBtn').onclick=scanDip;init().catch(e=>$('status').textContent='Hata: '+e.message);
