const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const fmt=x=>Number.isFinite(Number(x))?Number(x).toLocaleString('tr-TR',{maximumFractionDigits:2}):'-';
let scanRows=[];
async function fetchJson(url){const res=await fetch(url); const text=await res.text(); try{return JSON.parse(text);}catch{throw new Error('API JSON döndürmedi: '+text.slice(0,120));}}
function setStatus(t){$('#status').textContent=t;}
function setTab(id){$$('.page').forEach(x=>x.classList.add('hidden')); $('#'+id).classList.remove('hidden'); $$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));}
$$('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
async function analyze(){
 const symbol=($('#symbol').value||'PAPIL').toUpperCase(); setStatus(symbol+' analiz ediliyor...');
 try{const j=await fetchJson('/api/stock?symbol='+symbol); if(!j.success) throw new Error(j.error||'Veri yok'); renderAnalysis(j.analysis); setStatus('Analiz tamamlandı: '+symbol);}catch(e){setStatus('Veri alınamadı: '+e.message);}
}
function renderAnalysis(a){
 $('#decision').textContent=a.decision; $('#aiScore').textContent=a.aiGeneral; $('#risk').textContent=a.risk; $('#prob').textContent='%'+a.probability;
 $('#priceLine').innerHTML=`<b>${a.symbol}</b> Son fiyat: ${fmt(a.close)} TL · Değişim: <span class="${a.change>=0?'good':'bad'}">${fmt(a.change)}%</span> · Hedef: ${fmt(a.target)} · Stop: ${fmt(a.stop)}`;
 renderLayers(a.layers); renderWhy(a); drawChart(a.ohlcv,a); renderTable('#indicatorTable',[['RSI',a.rsi],['MACD',a.macd],['ADX',a.adx],['+DI',a.pdi],['-DI',a.mdi],['MFI',a.mfi],['ROC',a.roc],['CCI',a.cci],['ATR %',a.atrPct],['SuperTrend',a.superTrendDir===1?'AL':'SAT']]);
 $('#aiComment').textContent=a.aiComment; $('#patternBox').innerHTML=`<b>${a.pattern.name}</b><br>Güven: ${a.pattern.confidence}/100 · Hedef: ${fmt(a.pattern.target)} · Stop: ${fmt(a.pattern.stop)}<br>${(a.pattern.notes||[]).join(' · ')}`;
 $('#backtestBox').innerHTML=`Başarı oranı: <b>${a.backtest.successRate}%</b><br>Sinyal: ${a.backtest.signals} · Başarılı: ${a.backtest.success}<br>Ortalama getiri: ${a.backtest.avgReturn}% · Maks. düşüş: ${a.backtest.maxDrawdown}% · Risk/Getiri: ${a.backtest.riskReward}`;
}
function renderLayers(l){ const names={trend:'Trend',momentum:'Momentum',money:'Para Girişi',volatility:'Volatilite',pattern:'Formasyon',backtest:'Backtest',kapNews:'Haber/KAP',financial:'Finansal',sector:'Sektör',learning:'Öğrenen AI'}; $('#layers').innerHTML=Object.entries(l).map(([k,v])=>`<div class="layer"><span>${names[k]||k}</span><div class="track"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`).join('');}
function renderWhy(a){$('#whyList').innerHTML=`<div class="good">${(a.positives||[]).map(x=>'✓ '+x).join('<br>')}</div><br><div class="bad">${(a.negatives||[]).map(x=>'✗ '+x).join('<br>')}</div>`;}
function renderTable(sel,rows){$(sel).innerHTML='<tbody>'+rows.map(r=>`<tr><th>${r[0]}</th><td>${fmt(r[1])}</td></tr>`).join('')+'</tbody>';}
function drawChart(rows,a){const cv=$('#chart'),ctx=cv.getContext('2d'),w=cv.width=cv.clientWidth*2,h=cv.height=cv.clientHeight*2;ctx.clearRect(0,0,w,h); if(!rows?.length)return; const pad=50, vals=rows.flatMap(r=>[r.high,r.low]).concat([a.ema20,a.ema50,a.ema200].filter(Number.isFinite)); const min=Math.min(...vals), max=Math.max(...vals); const x=i=>pad+i*(w-pad*2)/(rows.length-1); const y=v=>h-pad-(v-min)*(h-pad*2)/(max-min||1); ctx.strokeStyle='#1f3859'; ctx.lineWidth=1; for(let i=0;i<5;i++){let yy=pad+i*(h-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(w-pad,yy);ctx.stroke();}
 rows.forEach((r,i)=>{const xx=x(i), open=y(r.open), close=y(r.close), hi=y(r.high), lo=y(r.low), up=r.close>=r.open; ctx.strokeStyle=up?'#38d17a':'#ff6673'; ctx.fillStyle=ctx.strokeStyle; ctx.beginPath();ctx.moveTo(xx,hi);ctx.lineTo(xx,lo);ctx.stroke(); ctx.fillRect(xx-3,Math.min(open,close),6,Math.max(2,Math.abs(close-open)));});
 function line(key,color){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath(); rows.forEach((r,i)=>{const v=r[key]; if(!Number.isFinite(v))return; const xx=x(i), yy=y(v); i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);});ctx.stroke();}
 // basit EMA çizgileri son değerleri sabit yerine kapanışlardan tekrar hesaplamamak için gösterge notu olarak ana panelde verilir.
 ctx.fillStyle='#93a4bd';ctx.font='22px Arial';ctx.fillText('Mum Grafik · EMA/Bollinger/VWAP göstergeleri analiz motorunda hesaplanır',pad,32);
}
async function scanAll(){scanRows=[]; $('#scanBody').innerHTML=''; const totalJ=await fetchJson('/api/symbols'); const total=totalJ.total||0; let offset=0,limit=4; setStatus('Tarama başladı...'); while(offset<total){try{const j=await fetchJson(`/api/scan?offset=${offset}&limit=${limit}`); if(j.data) scanRows.push(...j.data); offset+=limit; const pct=Math.min(100,Math.round(offset/total*100)); $('#progress i').style.width=pct+'%'; setStatus(`${Math.min(offset,total)} / ${total} hisse tarandı`); renderScan(); await new Promise(r=>setTimeout(r,80));}catch(e){setStatus('Tarama hatası: '+e.message);break;}} renderBaskets();}
function renderScan(){const rows=[...scanRows].sort((a,b)=>(b.aiGeneral||0)-(a.aiGeneral||0)); $('#scanBody').innerHTML=rows.slice(0,120).map((r,i)=>`<tr><td>${i+1}</td><td>${r.symbol}</td><td>${fmt(r.aiGeneral)}</td><td>${r.decision}</td><td>${fmt(r.probability)}%</td><td>${fmt(r.risk)}</td><td>${fmt(r.expectedReturn)}%</td><td>${r.pattern||'-'}</td></tr>`).join(''); $('#top20').innerHTML=rows.slice(0,20).map(r=>`<span class="pill">${r.symbol} ${r.aiGeneral}</span>`).join(' ');}
function renderBaskets(){const rows=[...scanRows]; const safe=rows.filter(r=>r.aiGeneral>=65&&r.risk<=40).sort((a,b)=>b.aiGeneral-a.aiGeneral).slice(0,10); const opp=rows.filter(r=>r.expectedReturn>=8&&r.risk<=65).sort((a,b)=>(b.expectedReturn||0)-(a.expectedReturn||0)).slice(0,10); const trade=rows.filter(r=>r.probability>=60).sort((a,b)=>(b.probability||0)-(a.probability||0)).slice(0,10); $('#safeList').innerHTML=safe.map(r=>`<div class="pill">${r.symbol} · AI ${r.aiGeneral} · Risk ${r.risk}</div>`).join(''); $('#oppList').innerHTML=opp.map(r=>`<div class="pill">${r.symbol} · Getiri ${fmt(r.expectedReturn)}%</div>`).join(''); $('#tradeList').innerHTML=trade.map(r=>`<div class="pill">${r.symbol} · Olasılık ${fmt(r.probability)}%</div>`).join('');}
async function portfolio(){const syms=$('#portfolioSymbols').value||'MRSHL,PAPIL,TEZOL,USAK,VKING'; const j=await fetchJson('/api/portfolio-advice?symbols='+encodeURIComponent(syms)); $('#portfolioSummary').textContent=j.summary||''; $('#portfolioBody').innerHTML=(j.data||[]).map(r=>`<tr><td>${r.symbol}</td><td>${r.decision||'-'}</td><td>${fmt(r.aiGeneral)}</td><td>${fmt(r.risk)}</td><td>${fmt(r.probability)}%</td><td>${fmt(r.target)}</td><td>${fmt(r.stop)}</td></tr>`).join('');}
async function learning(){const j=await fetchJson('/api/learning'); $('#learningBox').innerHTML=(j.memory.yearlyPerformance||[]).map(y=>`${y.year}: ${y.success}/${y.signals} başarı · Ortalama getiri ${y.avgReturn}% · En iyi kural: ${y.bestRule}`).join('<br>')+'<hr>'+ (j.bestRules||[]).map(r=>`${r.rule}: %${r.successRate}`).join('<br>');}
$('#btnAnalyze').onclick=analyze; $('#btnScan').onclick=scanAll; $('#btnPortfolio').onclick=portfolio; $('#btnLearning').onclick=learning; analyze(); learning();
