
import {avg,clamp} from './utils.js';
export function sma(values,period){return values.map((_,i)=>i+1<period?null:avg(values.slice(i-period+1,i+1)));}
export function ema(values,period){const k=2/(period+1);let e=null;return values.map((v,i)=>{v=Number(v)||0;if(i===0)e=v;else e=v*k+e*(1-k);return e;});}
export function rsi(closes,period=14){let gains=[],losses=[];for(let i=1;i<closes.length;i++){const d=closes[i]-closes[i-1];gains.push(Math.max(0,d));losses.push(Math.max(0,-d));}const out=[null];for(let i=0;i<gains.length;i++){if(i+1<period){out.push(null);continue;}const g=avg(gains.slice(i-period+1,i+1)),l=avg(losses.slice(i-period+1,i+1));out.push(l===0?100:100-(100/(1+g/l)));}return out;}
export function macd(closes){const e12=ema(closes,12),e26=ema(closes,26);const line=closes.map((_,i)=>e12[i]-e26[i]);const signal=ema(line,9);const hist=line.map((v,i)=>v-signal[i]);return{line,signal,hist};}
export function atr(rows,period=14){const tr=rows.map((r,i)=>{if(i===0)return r.high-r.low;const p=rows[i-1].close;return Math.max(r.high-r.low,Math.abs(r.high-p),Math.abs(r.low-p));});return sma(tr,period).map((v,i)=>v??tr[i]);}
export function bollinger(closes,period=20,mult=2){const mid=sma(closes,period);return closes.map((_,i)=>{if(i+1<period)return{mid:null,upper:null,lower:null,width:null};const slice=closes.slice(i-period+1,i+1),m=mid[i];const sd=Math.sqrt(avg(slice.map(x=>(x-m)**2)));return{mid:m,upper:m+mult*sd,lower:m-mult*sd,width:m?((mult*2*sd)/m)*100:0};});}
export function obv(rows){let o=0;return rows.map((r,i)=>{if(i>0){if(r.close>rows[i-1].close)o+=r.volume;else if(r.close<rows[i-1].close)o-=r.volume;}return o;});}
export function mfi(rows,period=14){const tp=rows.map(r=>(r.high+r.low+r.close)/3),mf=rows.map((r,i)=>tp[i]*r.volume);return rows.map((_,i)=>{if(i<period)return null;let pos=0,neg=0;for(let j=i-period+1;j<=i;j++){if(tp[j]>tp[j-1])pos+=mf[j];else if(tp[j]<tp[j-1])neg+=mf[j];}if(neg===0)return 100;const ratio=pos/neg;return 100-(100/(1+ratio));});}
export function adxLite(rows,period=14){const plus=[],minus=[];for(let i=1;i<rows.length;i++){const up=rows[i].high-rows[i-1].high,down=rows[i-1].low-rows[i].low;plus.push(up>down&&up>0?up:0);minus.push(down>up&&down>0?down:0);}const pdi=[null],mdi=[null],adx=[null];for(let i=0;i<plus.length;i++){if(i+1<period){pdi.push(null);mdi.push(null);adx.push(null);continue;}const p=avg(plus.slice(i-period+1,i+1))*100,m=avg(minus.slice(i-period+1,i+1))*100;pdi.push(clamp(p,0,100));mdi.push(clamp(m,0,100));adx.push(clamp(Math.abs(p-m),0,60));}return{adx,pdi,mdi};}
export function vwap(rows,period=20){return rows.map((_,i)=>{const s=rows.slice(Math.max(0,i-period+1),i+1);const pv=s.reduce((a,r)=>a+((r.high+r.low+r.close)/3)*r.volume,0);const vv=s.reduce((a,r)=>a+r.volume,0);return vv?pv/vv:null;});}
