import {avg,sma,ema,stdev,pct} from './math.js';
export function rsi(c,n=14){let out=Array(c.length).fill(null);for(let i=n;i<c.length;i++){let g=0,l=0;for(let j=i-n+1;j<=i;j++){let d=c[j]-c[j-1]; if(d>0)g+=d; else l-=d;} let rs=l===0?100:g/l; out[i]=100-(100/(1+rs));} return out;}
export function macd(c){const e12=ema(c,12),e26=ema(c,26); const m=c.map((_,i)=>e12[i]-e26[i]); const s=ema(m,9); return {macd:m,signal:s,hist:m.map((v,i)=>v-s[i])};}
export function atr(h,l,c,n=14){const tr=c.map((_,i)=>i?Math.max(h[i]-l[i],Math.abs(h[i]-c[i-1]),Math.abs(l[i]-c[i-1])):h[i]-l[i]);return sma(tr,n);}
export function obv(c,v){let out=[0]; for(let i=1;i<c.length;i++) out[i]=out[i-1]+(c[i]>c[i-1]?v[i]:c[i]<c[i-1]?-v[i]:0); return out;}
export function mfi(h,l,c,v,n=14){const tp=c.map((x,i)=>(h[i]+l[i]+x)/3);let out=Array(c.length).fill(null);for(let i=n;i<c.length;i++){let pos=0,neg=0;for(let j=i-n+1;j<=i;j++){let mf=tp[j]*v[j]; if(tp[j]>tp[j-1])pos+=mf; else neg+=mf;} out[i]=100-(100/(1+pos/(neg||1)));} return out;}
export function roc(c,n=12){return c.map((x,i)=>i<n?null:pct(x,c[i-n]));}
export function cci(h,l,c,n=20){const tp=c.map((x,i)=>(h[i]+l[i]+x)/3);let out=Array(c.length).fill(null); for(let i=n-1;i<c.length;i++){const arr=tp.slice(i-n+1,i+1), ma=avg(arr), md=avg(arr.map(x=>Math.abs(x-ma))); out[i]=md?(tp[i]-ma)/(0.015*md):0;} return out;}
export function bollinger(c,n=20,k=2){const mid=sma(c,n); return c.map((_,i)=>{ if(i<n-1) return {mid:null,upper:null,lower:null}; const arr=c.slice(i-n+1,i+1); const sd=stdev(arr); return {mid:mid[i], upper:mid[i]+k*sd, lower:mid[i]-k*sd}; });}
export function donchian(h,l,n=20){return h.map((_,i)=>({upper:Math.max(...h.slice(Math.max(0,i-n+1),i+1)), lower:Math.min(...l.slice(Math.max(0,i-n+1),i+1))}));}
export function adx(h,l,c,n=14){const pdi=Array(c.length).fill(null), mdi=Array(c.length).fill(null), adx=Array(c.length).fill(null); let pdm=[], mdm=[], tr=[]; for(let i=1;i<c.length;i++){const up=h[i]-h[i-1], dn=l[i-1]-l[i]; pdm[i]=up>dn&&up>0?up:0; mdm[i]=dn>up&&dn>0?dn:0; tr[i]=Math.max(h[i]-l[i],Math.abs(h[i]-c[i-1]),Math.abs(l[i]-c[i-1]));}
 for(let i=n;i<c.length;i++){const atr=avg(tr.slice(i-n+1,i+1)); const p=100*avg(pdm.slice(i-n+1,i+1))/(atr||1); const m=100*avg(mdm.slice(i-n+1,i+1))/(atr||1); pdi[i]=p; mdi[i]=m; const dx=100*Math.abs(p-m)/((p+m)||1); adx[i]=i===n?dx:(adx[i-1]*(n-1)+dx)/n;} return {adx,pdi,mdi};}
export function superTrend(h,l,c,n=10,m=3){const at=atr(h,l,c,n); const dir=Array(c.length).fill(1), line=Array(c.length).fill(null); for(let i=0;i<c.length;i++){const mid=(h[i]+l[i])/2; const upper=mid+(at[i]||0)*m, lower=mid-(at[i]||0)*m; if(i===0){line[i]=lower; continue;} dir[i]=c[i]>(line[i-1]||0)?1:c[i]<(line[i-1]||0)?-1:dir[i-1]; line[i]=dir[i]===1?Math.max(lower,line[i-1]||lower):Math.min(upper,line[i-1]||upper);} return {line,dir};}
