// R17 Provider Abstraction Layer - BIST symbol universe
// Only symbol codes are stored here. Price/OHLCV data is fetched live by lib/unified-provider.js.
const SYMBOLS = `
ACSEL ADEL ADESE AEFES AFYON AGESA AGHOL AGROT AHGAZ AHSGY AKBNK AKCNS AKENR AKFGY AKFYE AKGRT AKMGY AKSA
AKSEN AKSGY AKSUE AKYHO ALARK ALBRK ALCAR ALCTL ALFAS ALGYO ALKA ALKIM ALMAD ALTNY ANELE ANGEN ANHYT ANSGR
ARASE ARCLK ARDYZ ARENA ARSAN ARTMS ARZUM ASELS ASGYO ASTOR ASUZU ATAGY ATAKP ATATP ATEKS ATLAS ATSYH AVGYO
AVHOL AVOD AVPGY AVTUR AYDEM AYEN AYES AYGAZ AZTEK BAGFS BAKAB BALAT BANVT BARMA BASCM BASGZ BAYRK BEGYO
BERA BEYAZ BFREN BIENY BIGCH BIMAS BINHO BIOEN BIZIM BJKAS BLCYT BMSCH BMSTL BNTAS BOBET BORLS BOSSA BRISA
BRKO BRKS BRKVY BRLSM BRMEN BRSAN BRYAT BSOKE BTCIM BUCIM BURCE BURVA BVSAN BYDNR CANTE CASAA CCOLA CELHA
CEMAS CEMTS CEOEM CIMSA CLEBI CMBTN CMENT CONSE COSMO CRDFA CRFSA CUSAN CVKMD CWENE DAGHL DAGI DAPGM DARDL
DENGE DERHL DERIM DESA DESPC DEVA DGATE DGGYO DGNMO DIRIT DITAS DMIST DMSAS DNISI DOAS DOBUR DOCO DOFER
DOGUB DOHOL DOKTA DURDO DYOBY DZGYO EBEBK ECILC ECZYT EDATA EDIP EFORC EGEEN EGEPO EGGUB EGPRO EGSER EKIZ
EKOS EKSUN ELITE EMKEL ENERY ENJSA ENKAI ENSRI EPLAS ERBOS ERCB EREGL ERSU ESCAR ESCOM ESEN ETILR EUHOL
EUPWR EUREN EUYO EYGYO FADE FENER FLAP FMIZP FONET FORMT FRIGO FROTO FZLGY GARAN GARFA GEDIK GEDZA GENTS
GEREL GLBMD GLRYH GLYHO GMTAS GOKNR GOLTS GOODY GOZDE GRNYO GRSEL GRTRK GSDDE GSDHO GSRAY GUBRF GWIND GZNMI
HALKB HATEK HATSN HDFGS HEDEF HEKTS HKTM HLZYO HUNER HURGZ ICBCT ICUGS IDEAS IDGYO IEYHO IHAAS IHEVA IHGZT
IHLAS IHLGM IHYAY IMASM INDES INFO INGRM INTEM INVEO INVES IPEKE ISATR ISBIR ISBTR ISCTR ISDMR ISFIN ISGSY
ISGYO ISKPL ISMEN ISSEN ISYAT IZENR IZFAS IZINV IZMDC JANTS KAPLM KAREL KARSN KARTN KATMR KAYSE KBORU KCAER
KCHOL KENT KERVN KERVT KFEIN KGYO KIMMR KLGYO KLKIM KLMSN KLNMA KLRHO KLSER KLSYN KMPUR KNFRT KONKA KONTR
KONYA KOPOL KORDS KOZAA KOZAL KRDMA KRDMB KRDMD KRGYO KRONT KRPLS KRSTL KRTEK KRVGD KSTUR KTLEV KTSKR KUTPO
KUYAS KZBGY KZGYO LIDER LIDFA LINK LKMNH LOGO LRSHO LUKSK MAALT MACKO MAGEN MAKIM MAKTK MANAS MARBL MARKA
MARTI MAVI MEDTR MEGAP MEGMT MEKAG MEPET MERCN MERIT MERKO METRO METUR MGROS MHRGY MIATK MIPAZ MNDRS MNDTR
MOBTL MOGAN MPARK MRSHL MSGYO MTRKS MTRYO MZHLD NATEN NETAS NIBAS NTGAZ NTHOL NUGYO NUHCM OBAMS ODAS OFSYM
ONCSM ORCAY ORGE ORMAK OSMEN OSTIM OTKAR OTTO OYAKC OYAYO OYLUM OYYAT OZATD OZKGY OZRDN OZSUB PAGYO PAMEL
PAPIL PARSN PASEU PCILT PEKGY PENGD PENTA PETKM PETUN PGSUS PINSU PKART PKENT PLTUR PNSUT POLHO POLTK PRDGS
PRKAB PRKME PRZMA PSDTC PSGYO QNBFB QNBFL QUAGR RALYH RAYSG REEDR RGYAS RNPOL RODRG RTALB RUBNS RYGYO RYSAS
SAFKR SAHOL SAMAT SANEL SANKO SARKY SASA SAYAS SDTTR SEKFK SEKUR SELEC SELGD SELVA SEYKM SILVR SIROK SKBNK
SKTAS SKYLP SMART SMRTG SNGYO SNICA SNPAM SOKE SOKM SONME SRVGY SUMAS SUNTK SURGY SUWEN TABGD TARKM TATEN
TATGD TAVHL TBORG TCELL TDGYO TEKTU TERA TEZOL TGSAS THYAO TKFEN TKNSA TLMAN TMPOL TMSN TNZTP TOASO TRCAS
TRGYO TRILC TSPOR TTKOM TTRAK TUCLK TUKAS TUPRS TURGG TURSG UFUK ULAS ULKER ULUSE ULUUN UNLU USAK UZERB
VAKBN VAKFN VAKKO VANGD VBTYZ VERTU VERUS VESBE VESTL VKFYO VKGYO VKING VRGYO YAPRK YATAS YAYLA YESIL YGGYO
YGYO YKBNK YKSLN YONGA YUNSA YYAPI YYLGD ZEDUR ZOREN ZRGYO
`.split(/\s+/).map(s=>s.trim()).filter(Boolean);

module.exports = { SYMBOLS: Array.from(new Set(SYMBOLS)) };
